version: "3"
services:
  app:
    image: malvi/asp-chef-cli:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:rw
    network_mode: host
    ports:
      - 8000:8000
